# Generated by Django 4.2.3 on 2023-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackrx', '0012_alter_marketingcampaigns_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedleads',
            name='highlights',
            field=models.TextField(blank=True, default=''),
        ),
    ]
